### ISSUE TITLE
Convert ICES special request functions to current RDBES data format

### ISSUE THREAD

**Issue by davidcurrie2001** [ices-tools-dev/icesRDBES#11]
Convert the example functions written for the ICES Special Request <https://www.ices.dk/sites/pub/Publication%20Reports/Expert%20Group%20Report/EOSG/2020/Annex%203_WKRDBEST2_2020.pdf> to the current RDBES format.

Code used in the Special Request can be found at <https://github.com/ices-eg/WK_RDBES/tree/master/Special_Request_20_05>

**Comment by davidcurrie2001** [comment]
I have migrated the selection method summary code to the new format and put a function and example report in <https://github.com/ices-tools-dev/icesRDBES/tree/dev/WGRDBES-EST/personal/David>

**Comment by nmprista** [comment]
wgrdbes-est 2022: vague - will be picked up as specific issue in future when becomes needed
