### ISSUE TITLE
Add datasets based on Lohr

### ISSUE THREAD

**Issue by KirstenBirchHaakansson** [ices-tools-dev/icesRDBES#17]
Convert a simple data set from Lohr to the RDBES data

**Comment by KirstenBirchHaakansson** [comment]
According to the license attached to Lohr's data, then we can not use it as test data

**Comment by KirstenBirchHaakansson** [comment]
In the SDAResources package there are Lohr datasets from the 3rd edition of the book with a public license, so it should be ok to use these

**Comment by KirstenBirchHaakansson** [comment]
and maybe Lumley

**Comment by nmprista** [comment]
General. I close the issue - specific issues to be created for each datasets we develop
