### ISSUE TITLE
Rename findAndKillOrphans?

### ISSUE THREAD

**Issue by nmprista** [ices-tools-dev/icesRDBES#2]
findAndRemoveLooseRows (or something of the sort) could be more descriptive alternative?

**Comment by davidcurrie2001** [comment]
It made me very happy to write a function called "findAndKillOrphans" so I would prefer not to sanitise it :-) I'll go with the wider group decision though.

**Comment by nmprista** [comment]
I had a laugh at it and if others do too, think it will be worth keeping; in summary, worth a small discussion in the wider group when we have time but not more. Great if you don't make changes at this moment.
