### ISSUE TITLE
Update tests/test data/code for latest version of the RDBES data model

### ISSUE THREAD

**Issue by davidcurrie2001** [ices-tools-dev/icesRDBES#28]
- [x] Create new test data
- [x] Update tests to use the new test data
- [x] Update any configuration files with the latest data model
- [x] Update vignettes to use new test data

**Comment by nmprista** [comment]
@davidcurrie2001 I tested vignette "Raw Data Import" with testthat data and my own data and seems to be working. Only thing is that the new zip files now include the CS together with SL and VD. Maybe update the example and to keep the demo you already replace current HVD_*.zip and HSL_*.zip for a HCL_*.zip and HCE_*.zip?

**Comment by nmprista** [comment]
comment above was move into a specific issue
