### ISSUE TITLE
File paths - use `/` not `\\` 

### ISSUE THREAD

**Issue by nicholascarey** [ices-tools-dev/icesRDBES#32]
Using `//` (escaped forward slash) to construct file paths works on Windows but not on macOS.   Can be replaced with single `\` (backslash) which works on either (as far as I can tell, at least on my Mac and work PC).  This would eventually cause issues with build tests and CRAN because it builds against macOS. (and also i prefer to work on Mac  🙂 )

Currently used in:
- `createRDBESRawObject`
- Most vignettes
- Most tests

**Comment by rix133** [comment]
its / not \

**Comment by nicholascarey** [comment]
Fixed in 6a4ff786200efc8f31d5f37e8bbd152e87ef5276

**Comment by Jonathan-rault** [comment]
I think there are still remaining some of them in the vignette Rmd files
