### ISSUE TITLE
Core preparation functions need testing

### ISSUE THREAD

**Issue by nmprista** [ices-tools-dev/icesRDBES#5]
code and example script can be found here
https://github.com/ices-tools-dev/icesRDBES/tree/main/WGRDBES-EST/personal/Nuno

**Comment by davidcurrie2001** [comment]
@nmprista Currently applyGenerateProbs() is returning a list but should be returning an RDBESRawObject (which is what it's given as a parameter).  If you change the last few lines as follows it will return the correct object type:
```
...
    #x[[i]]  <- do.call("rbind", ls2)
    x[[i]] <- data.table::setDT(do.call("rbind", ls2))
  }
  print("========end generateProbs=======")

  # Return an edited version of the object we were given, not a new list
  #lapply(x, function(x) if (!is.null(x)) data.table::data.table(x) else x)
  x

```

**Comment by davidcurrie2001** [comment]
@nmprista  Removing the prefixes from all the fields will result in an object that fails validation:  
```
icesRDBES::validateRDBESRawObject(myH7PrepObject, verbose = FALSE)
[1] "objectToCheck contains the following tables which don't contain all required fields: DE,SD,OS,LE,SS,SA,FM,BV,VD,SL"
[1] FALSE
```

I think you either need to work with fields with the prefixes; or remove them during interim steps, but add them back in at the final step; or define a new object type for RDBESPrepObject.  I think the last option will be a bit pointless and would prefer it if the prepared object was also an RDBESRawObject - makes things simpler.

**Comment by davidcurrie2001** [comment]
@nmprista For my RDBESRawObject manipulation functions I have added something like this as one of the first lines:
```
  # Check we have a valid RDBESRawObject before doing anything else
  if (!validateRDBESRawObject(rdbesRawObjectToFilter, verbose = FALSE)) {
    stop(paste0(
      "rdbesRawObjectToFilter is not valid ",
      "- filterRDBESRawObject will not proceed"
    ))
  }
```
This is an easy way to check that we are dealing with a valid input RDBESRawObject before going any further in the function.

**Comment by davidcurrie2001** [comment]
in generateZerosUsingSL() I don't think trying to add decimal places to the SAid will work correctly - it will produce an invalid RDBESRawObject.  Perhaps negative integers could be used instead to avoid conflicts with any existing SAid values?  Similarly SAsquenceNumber is defined as an integer in the RDBES documentation.  Perhaps it makes sense just to keep that value the same as the original record?
You can't assume that SAunitName is always the same as the SAid because in general it won't be and that field is a string (e.g. your SAunitName could be "CTB/2021/tcca") - perhaps some text could be appended to SAunitName to show this is a row that has been generated by the function?

**Comment by davidcurrie2001** [comment]
@nmprista The icesRDBES package has the list of tables in each hierarchy within "tablesInRDBESHierarchies" in the data folder.  You can use this to work out which tables you need to check in your runChecksOnSelectionAndProbs() function e.g. 
```
hierarchyToCheck <- paste0("H",x[["DE"]]$hierarchy[1]))
# hierarchyToCheck <- "H7"
targetTables <- tablesInRDBESHierarchies[[hierarchyToCheck]]
targetTables <- targetTables[targetTables!="DE"]
parentId <- paste0(targetTables,"id")
targetTables <- targetTables[targetTables!="SD"]
parentId <-parentId[parentId!="BVid"]
```

At the moment tablesInRDBESHierarchies doesn't indicate whether a table is mandatory within the hierarchy - however we will need to indicate this so we can handle the cases where tables are sometimes present in the hierarchy, and sometimes not.  You will also need to work out whether you are dealing with lower hierarchy A, B, C, or D to know which tables to expect after SA for a given record.

**Comment by nmprista** [comment]
@davidcurrie2001 the functions were moved from wgrdes-est/personal to core directories in dev

**Comment by nmprista** [comment]
> In generateZerosUsingSL() I don't think trying to add decimal places to the SAid will work correctly - it will produce an invalid RDBESRawObject. Perhaps negative integers could be used instead to avoid conflicts with any existing SAid values? Similarly SAsquenceNumber is defined as an integer in the RDBES documentation. Perhaps it makes sense just to keep that value the same as the original record?

@davidcurrie2001 You have a point with regards the validation, but moving them from decimal to negatives will preclude the ordering of the "new" species records together into a sample which seems quite useful.  how should we go around it: will it be possible to build a generic validateRDBESObjects with options for "raw" and "preparation" (and "estimation"?);  alternatively, setkey on the decimals and then "hide them" under negatives? The last dones not seem very practical. I am open to suggestions.

**Comment by davidcurrie2001** [comment]
I'm taking a look at this today - I think it probably easiest to allow correct validation on numerical SAid, and SAsequenceNumber values (rather than just integers).

**Comment by davidcurrie2001** [comment]
I've just pushed some changes that incorporate the things we have discussed on this thread.  The code also just uses the normal column names now (i.e. it doesn't need to remove the prefixes).  The vignette "calc-zeroes-and-probs.Rmd" shows it running on your example data and producing valid output.

**Comment by nmprista** [comment]
wgrdes-est 2022 discussion: issue general. can be closed
