### ISSUE TITLE
Package data load issues 

### ISSUE THREAD

**Issue by nicholascarey** [ices-tools-dev/icesRDBES#53]
Some package data (`mapColNamesFieldR` at least, maybe others) fails to be called when the package is not loaded and a function is called using `::`

```
H5obj <- icesRDBES::createRDBESDataObject("./tests/testthat/h5_v_1_19_13")
```

```
Error in icesRDBES::createRDBESDataObject("./tests/testthat/h5_v_1_19_13") : 
  object 'mapColNamesFieldR' not found
```

Possibly related to this being  a `.RData` file rather than a `.rda` file? I've never seen this issue but i've only ever used `rda` for including data. Lazy loading is in place so this should work.

**Comment by rix133** [comment]
agree with that all data should be` .rda`

**Comment by nicholascarey** [comment]
I also made the 2 shrimps datasets `rda`. Not merged yet
