### ISSUE TITLE
`validateRDBESDataObject` - returns a `TRUE/FALSE` value rather than original input

### ISSUE THREAD

**Issue by nicholascarey** [ices-tools-dev/icesRDBES#56]
This is potentially confusing and unnecessary? Not sure why it needs to output this as a value rather than just a console message. 

In this case the RDBES object is overwritten to a `TRUE` value (this literally just happened and we had to figure out why the code wasn't working). 

```
H1obj <- validateRDBESDataObject(H1obj, verbose = TRUE)
```

I think best practice for this type of validation function is to return the original unaltered object  (so `return(invisible(object))`) which would this case guard against this type of user error (and you can't stop people trying to assign things). 

What to do if `FALSE`?

**Comment by ptrptr** [comment]
Function updated
